### ISSUE TITLE
[Info] Referencement

### ISSUE THREAD

**Issue by funilrys** [Dawsey21/Lists#1]
Hello @Dawsey21 ,

Because I want to be transparent, I just wanted to inform you that we added `adblock-list.txt` to [Ultimate.Hosts.Blacklist](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist) through [Ultimate-Hosts-Blacklist/Spam404](https://github.com/Ultimate-Hosts-Blacklist/Spam404).

Cheers,
Nissar

P.S: Feel free to close/comment after reading this information.

**Comment by dnmTX** [comment]
@funilrys  i think it's better if you change the `"raw_link"` in `info.json` to:
https://raw.githubusercontent.com/Dawsey21/Lists/master/main-blacklist.txt

Cheers
