### ISSUE TITLE
Are the Spam404 lists still maintained?

### ISSUE THREAD

**Issue by 4oo4** [Dawsey21/Lists#2]
I had been using this list for a while and had been really happy with it, but noticed that there haven't been any commits since April. Will the lists start updating again at some point?

Cheers

**Comment by 4oo4** [comment]
Based on the non-response, I'll go ahead and guess that the answer is no. Your lists were really good to use, sad to see them go.

**Comment by ccuser44** [comment]
> I had been using this list for a while and had been really happy with it, but noticed that there haven't been any commits since April. Will the lists start updating again at some point?
> 

This is a fake spam404 repo

**Comment by 4oo4** [comment]
> > I had been using this list for a while and had been really happy with it, but noticed that there haven't been any commits since April. Will the lists start updating again at some point?
> 
> This is a fake spam404 repo

Is there a real one then?
